plugins {
    id 'java'
    id 'idea'
    id 'jacoco'
}

allprojects {
    group = 'com.ak'
    apply plugin: 'idea'
    idea {
        module {
            inheritOutputDirs = true
            downloadJavadoc = true
            downloadSources = true
        }
    }

    sourceSets {
        main.output.resourcesDir = main.java.classesDirectory
    }
}

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(27)
        }
    }

    compileJava {
        options.encoding = 'UTF-8'
        options.compilerArgs << '-parameters'
    }

    compileTestJava {
        options.encoding = 'UTF-8'
    }

    test {
        forkEvery = 5
        useJUnitPlatform()
        testLogging {
            events 'failed'
        }
        maxHeapSize = '1G'
    }
}