pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url = 'https://jitpack.io' }
        maven {
            url = "https://artifacts.codegenomeproject.org/maven"
            credentials {
                username = providers.environmentVariable('CODE_GENOME_USERNAME').orElse(providers.gradleProperty('codeGenomeUsername')).getOrNull()
                password = providers.environmentVariable('CODE_GENOME_TOKEN').orElse(providers.gradleProperty('codeGenomeToken')).getOrNull()
            }
        }
    }
}

plugins {
    id("com.autonomousapps.build-health") version '3.19.1'
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven { url = 'https://jitpack.io' }
    }
}

rootProject.name = 'DesktopFX'
include 'Util'
include 'Communication'
include 'FxCore'
include 'Desktop'