plugins {
    id 'java-library'
    alias(libs.plugins.javafxplugin)
    alias(libs.plugins.openrewrite)
}

dependencies {
    api libs.javafx.base
    api project(':Util')
    api project(':Communication')
    compileOnly libs.jspecify

    testImplementation(platform(libs.junit))
    testImplementation libs.bundles.test.implementation
    testCompileOnly libs.bundles.test.compile
    testRuntimeOnly libs.bundles.test.runtime

    rewrite libs.rewrite.migrate.java
    rewrite libs.rewrite.testing.frameworks
}

rewrite {
    activeRecipe('org.openrewrite.java.migrate.UpgradeToJava25')
    activeRecipe('org.openrewrite.java.testing.assertj.JUnitToAssertj')
    activeRecipe('org.openrewrite.java.testing.assertj.Assertj')
    setExportDatatables(true)
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

javafx {
    version = '28-ea+6'
    modules = ['javafx.controls', 'javafx.graphics']
    configurations = ['api']
}