plugins {
    id 'java-library'
    alias(libs.plugins.openrewrite)
}

configurations {
    mockitoAgent
}

dependencies {
    api libs.measure.unit.api
    api libs.javax.json
    api libs.commons.math
    api libs.commons.csv
    compileOnly libs.jspecify
    runtimeOnly libs.logback
    implementation libs.slf4j
    implementation libs.tech.units
    implementation libs.jenetics
    implementation libs.commons.math4.legacy.core
    implementation libs.commons.rng.client.api
    implementation libs.commons.rng.simple

    testImplementation(platform(libs.junit))
    testImplementation libs.mockito.junit
    testImplementation libs.mockito.core
    testImplementation libs.bundles.test.implementation
    testCompileOnly libs.bundles.test.compile
    testRuntimeOnly libs.bundles.test.runtime

    rewrite libs.rewrite.testing.frameworks

    mockitoAgent(libs.mockito.core) {
        transitive = false
    }
}

rewrite {
    activeRecipe('org.openrewrite.java.testing.assertj.JUnitToAssertj')
    activeRecipe('org.openrewrite.java.testing.assertj.Assertj')
    setExportDatatables(true)
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

tasks {
    test {
        jvmArgs += "-javaagent:${configurations.mockitoAgent.asPath}"
    }
}