plugins {
    id 'java-library'
    alias(libs.plugins.openrewrite)
}

configurations {
    mockitoAgent
}

dependencies {
    api project(':Util')
    api libs.jserial.comm
    api libs.measure.unit.api
    api libs.javax.json
    compileOnly libs.jspecify
    implementation libs.tech.units

    testImplementation(platform(libs.junit))
    testImplementation libs.mockito.junit
    testImplementation libs.mockito.core
    testImplementation libs.bundles.test.implementation
    testCompileOnly libs.bundles.test.compile
    testRuntimeOnly libs.bundles.test.runtime

    rewrite libs.rewrite.testing.frameworks

    mockitoAgent(libs.mockito.core) {
        transitive = false
    }
}

rewrite {
    activeRecipe('org.openrewrite.java.testing.assertj.JUnitToAssertj')
    activeRecipe('org.openrewrite.java.testing.assertj.Assertj')
    setExportDatatables(true)
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

tasks.withType(Test).configureEach {
    jvmArgs('--enable-native-access=ALL-UNNAMED')
}

tasks.withType(JavaExec).configureEach {
    jvmArgs('--enable-native-access=ALL-UNNAMED')
}

tasks {
    test {
        jvmArgs += "-javaagent:${configurations.mockitoAgent.asPath}"
    }
}